=== scriptella/scriptella-etl/core/src/conf/scriptella/dtd/etl.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
%
 Copyright 2006-2012 The Scriptella Project Team.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
%
@title Scriptella ETL File DTD
@doctype etl SYSTEM "http://scriptella.org/dtd/etl.dtd"
@root etl
-->

<!--
Root element of Scriptella XML file.
<p><u>Example:</u><br>
A simple example of the script file with only one connection obtained via
JNDI bound datasource.
%
<etl>
    <connection driver="jndi" url="java:projectDS"/>
    <script>
        INSERT INTO Test VALUES (1, "One")
    </script>
</etl>

%
-->
<!ELEMENT etl (description?, properties?, connection*, (script*, query*)*)>

<!--
Contains description of ETL file.
-->
<!ELEMENT description (#PCDATA)>
<!--
The properties element contains a set of properties available for script elements.
The content of this element conforms to format supported by java.util.Properties.
This element may contain plain text or includes.
<p><u>Example:</u>
%
<properties>
    #standard properties syntax
    table.size=10
    tmp=c\:\\temp\\
    #including content from external properties file
    <include href="etl.properties"/>
</properties>

-->
<!ELEMENT properties (#PCDATA | include)*>
<!--
The connection element specifies connection to a database or other system.
This element may contain properties as plain text with includes.
<p><u>Example:</u>
%
<connection id="in" driver="com.octetstring.jdbcLdap.sql.JdbcLdapDriver"
            url="jdbc:ldap://localhost:389/dc=scriptella"
            user="cn=root,dc=scriptella" password="secret">
    SEARCH_SCOPE=subTreeScope
    ignore_transactions=true
</connection>

<connection driver="h2"
            url="jdbc:h2:db"
            user="sa" classpath="h2.jar"/>
%
-->
<!ELEMENT connection (#PCDATA | include)*>
<!--
 @attr id connection identifier. Connection is referenced by id in scripts and queries.
       For single connection ETL files this attribute is optional.
 @attr driver driver class name or alias. The default value is "auto",
       in this case a target driver is guessed from an url attribute.
 @attr url connection url.
 @attr user database login
 @attr password database password
 @attr catalog catalog
 @attr schema schema
 @attr classpath the classpath to use when loading the driver.
       Paths are colon/semicolon separated and resolved relative to a directory where ETL file resides.
       Absolute URLs are also supported, e.g. ftp://server/lib.jar
 @attr lazy-init <b>true</b> if connection initialization should be deferred until it is actually used.
       The default value of <b>false</b> means that connection is initialized on ETL startup.
-->
<!ATTLIST connection
id ID #IMPLIED
driver CDATA "auto"
url CDATA #IMPLIED
user CDATA #IMPLIED
password CDATA #IMPLIED
catalog CDATA #IMPLIED
schema CDATA #IMPLIED
classpath CDATA #IMPLIED
lazy-init (true | false) "false"
>
<!--
The fallback element contains alternate content to be used if the requested resource cannot be found.
This element may contain plain text or includes.
<p><u>Example:</u>
%
<include href="http://no-such-url/file.txt">
    <fallback> //First fallback
        <include href="localFile.txt>
            <fallback> //If alternative location also failed
                Failed to retrieve full text
            </fallback>
        </include>
    </fallback>
</include>
%
-->
<!ELEMENT fallback (#PCDATA | include)*>

<!--
The include element specifies content to include. Concept similar to XInclude.
<p><u>Examples:</u>
%
<include href="http://host/file.sql"><fallback>SHUTDOWN</fallback></include>
<include href="db/schema.sql"/>
%
-->
<!ELEMENT include (fallback?)>
<!--
@attr href contains an URI pointing to the file to include. URIs are resolved relative to ETL file.
@attr encoding Included text encoding name.
-->
<!ATTLIST include
href CDATA #REQUIRED
encoding CDATA #IMPLIED
>
<!--
The dialect element defines a vendor specific script. Scripting elements may contain any number of nested dialects.
This element may contain plain text or includes.
<u>Example:</u>
%
<dialect name="oracle" version="10\.">
    //Statements executed only for Oracle 10.x
</dialect>
<dialect name="oracle" exclude="true">
    //Statements executed for any datasource except Oracle
</dialect>

%
-->
<!ELEMENT dialect (#PCDATA | include)*>
<!--
 @attr name case insensitive regular expression to match vendor name, e.g. .*oracle.*
 @attr version case insensitive regular expression to match vendor version, e.g. 1\.0
 @attr exclude optional attribute to invert the name/version matching.
       Use exclude="true" to skip content for dialects with specified name and version.

-->
<!ATTLIST dialect
name CDATA #IMPLIED
version CDATA #IMPLIED
exclude (true | false) "false"
>

<!--
The onerror element defines fallback script to execute if error occurs.
This element may contain plain text or includes.
<p><u>Example:</u>
%
<onerror type="SQLException">
    DROP TABLE MYTABLE
</onerror>
%
Note: Attributes are applied using AND condition, so if you specified
%<onerror type="ProviderException" codes="100,200">%
so only exceptions with class name *.ProviderException having 100 and/or 200 error code are handled.
-->
<!ELEMENT onerror (#PCDATA | include | dialect)*>
<!--
 @attr type Regular expression pattern to match exception type. Partial matching is allowed.
 @attr codes Comma-separated list of vendor codes/sql states. Triggered if any of these codes matches one of the codes reported by driver.
 @attr message Regular expression pattern to match exception message. Partial matching is allowed.
 @attr retry true if statement which caused a problem should be retried after this handler completes.
 @attr connection-id optional connection ID. If omitted, the error handling code will be executed in the context of the current connection.
-->
<!ATTLIST onerror
type CDATA #IMPLIED
codes CDATA #IMPLIED
message CDATA #IMPLIED
retry (true | false) "false"
connection-id IDREF #IMPLIED
>

<!--
The query element is used to specify a query producing a result set.
This element may contain queries, scripts, plain text, includes and dialects.
<p><u>Example:</u><br>
Queries a table and writes the result into CSV file
%
<query connection-id="in">
   SELECT * FROM Test WHERE id=&#063;id
   <script connection-id="csv">
        $id,$value
   </script>
</query>
%
-->
<!ELEMENT query (#PCDATA | include | dialect | query | script)*>
<!--
 @attr connection-id references connection by identifier. The value of this attribute is inherited for nested elements.
       For single connection ETL files the connection-id is optional.
 @attr if expression to test. If result of evaluation is true - the element is evaluated, otherwise skipped.
        Use <a href="http://jakarta.apache.org/commons/jexl">JEXL</a> syntax for expressions.
 @attr id script identifier(name).
-->
<!ATTLIST query
connection-id IDREF #IMPLIED
if CDATA #IMPLIED
id ID #IMPLIED
>

<!--
The script element is used to specify a script.
This element may contain plain text,onerror handlers, includes and dialects.
<p><u>Example:</u><br>
Inserts a row into Test table if id>0
%
<script if="id>0">
    INSERT INTO Test VALUES(&#063;id, &#063;name)
</script>
%
-->
<!ELEMENT script (#PCDATA | include | dialect | onerror)*>
<!--
 @attr connection-id references connection by identifier. The value of this attribute is inherited for nested elements.
       For single connection ETL files the connection-id is optional.
 @attr new-tx true to use a separate connection for this script element. Opened lazily and reused across invocations; not committed after each invocation.
 @attr if expression to test. If result of evaluation is true - the element is evaluated, otherwise skipped.
        Use <a href="http://jakarta.apache.org/commons/jexl">JEXL</a> syntax for expressions.
 @attr id script identifier(name).
-->
<!ATTLIST script
connection-id IDREF #IMPLIED
new-tx (true | false) "false"
if CDATA #IMPLIED
id ID #IMPLIED
>

=== scriptella/scriptella-etl/core/src/test/scriptella/execution/ExecutionStatisticsTest.xml
<!DOCTYPE etl SYSTEM "http://scriptella.org/dtd/etl.dtd">
<etl>
    <connection driver="org.h2.Driver" url="jdbc:h2:mem:est;MODE=LEGACY;NON_KEYWORDS=VALUE" user="sa" password=""/>
    <script>
        create table t1 (
        id int
        );
        create table t2 (
        id int
        );
        insert into t1(id) values(1);
        insert into t1(id) values(2);
    </script>
    <query>
        select * from t1
        <query>
            select * from t1 where id=?id
            <script>
                insert into t2 values(?id)
            </script>
        </query>

    </query>
    <script>
        <!--Only H2 dialects are executed-->
        <dialect name="h2">
            COMMIT;<!--Just for test -->
            COMMIT;
        </dialect>
        <dialect name="h2">
        </dialect>
        <dialect name=".*oracle.*">
            Won't execute;
        </dialect>

    </script>


</etl>

=== scriptella/scriptella-etl/drivers/src/test/scriptella/driver/json/JsonExportTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etl SYSTEM "http://scriptella.org/dtd/etl.dtd">
<etl>
    <description>JSON export, dynamic includes and zero-row output contract.</description>
    <connection id="db" driver="h2" url="jdbc:h2:mem:json_phase3" user="sa"/>
    <connection id="out" driver="json" url="export.json"/>
    <connection id="in" driver="json" url="input.json"/>
    <connection id="transformed" driver="json" url="transformed.json"/>
    <connection id="existing" driver="json" url="existing.json"/>
    <connection id="absent" driver="json" url="absent.json"/>

    <query connection-id="db">
        SELECT * FROM (VALUES
            (2, 'second', CAST(7.25 AS DECIMAL(12,2))),
            (1, 'first', CAST(12.50 AS DECIMAL(12,2)))
        ) T("id", "template", "credit") ORDER BY "id"
        <script connection-id="out"><include href="${template}.json"/></script>
    </query>

    <query connection-id="in">
        response.customers
        <script connection-id="transformed">
            {"id": ?{row.id}, "items": ?{row.items},
             "note": ?{row.missing}, "literal": "${row.id}"}
        </script>
    </query>

    <query connection-id="db">
        SELECT 1 WHERE 1=0
        <script connection-id="existing">{}</script>
        <script connection-id="absent">{}</script>
    </query>
</etl>

=== scriptella/scriptella-etl/samples/ldap/jdbc/db2ldap.etl.xml
<!DOCTYPE etl SYSTEM "http://scriptella.org/dtd/etl.dtd">
<etl>
    <description>
        Migrates data from Database to LDAP.
        JdbcLdapDriver IMPORTANT NOTES:
        - Do not quote values in INSERT statements
        - Due to JdbcLdapDriver bug - do not insert extra spaces between attribute names ;)
    </description>
    <!--Connection to the in memory database-->
    <connection id="in" driver="org.h2.Driver" url="jdbc:h2:mem:indb;MODE=LEGACY;NON_KEYWORDS=VALUE"
                user="sa" password="" classpath="../lib/h2.jar"/>
    <!--Connection to the LDAP-->
    <connection id="out" driver="com.octetstring.jdbcLdap.sql.JdbcLdapDriver"
                url="jdbc:ldap://localhost:389"
                user="cn=root,dc=scriptella" password="secret" classpath="../lib/jdbcldap.jar">
        <!--Define connection properties-->
        SEARCH_SCOPE=subTreeScope
        ignore_transactions=true
        <!--You may embed properties into url using driver specific syntax, e.g.
         jdbc:ldap://localhost:389/dc=scriptella?SEARCH_SCOPE:=subTreeScope&amp;ignore_transactions:=true
         -->
    </connection>
    <script connection-id="in">
        <!-- Fills the in-memory database with initial data-->
        <include href="../dbschema.sql"/>
        INSERT INTO users VALUES ('jjones','janet');
        INSERT INTO users VALUES ('fbloggs','fred');
        INSERT INTO user_roles VALUES ('jjones','admin');
        INSERT INTO user_roles VALUES ('fbloggs','admin');
        INSERT INTO user_roles VALUES ('fbloggs','developer');
    </script>
    <script connection-id="out">
        <!-- Inserts top-level entry
        dn: dc=scriptella
        objectclass: dcObject
        objectclass: organization
        o: Company
        dc: scriptella
        -->
        INSERT INTO dc(objectClass,objectClass,o,dc) VALUES (dcObject,organization,Company,scriptella);

        <!--
        # Define an entry to contain people
        dn: ou=people,dc=scriptella
        objectClass: organizationalUnit
        ou: people
        -->
        INSERT INTO ou,dc=scriptella (objectClass,ou) VALUES (organizationalUnit,people);

        <!--
        # Define an entry to contain LDAP groups
        dn: ou=groups,dc=scriptella
        objectClass: organizationalUnit
        ou: groups
        -->
        INSERT INTO ou,dc=scriptella (objectClass,ou) VALUES (organizationalUnit,groups);

        <onerror message=".*already exists.*">
            --If entries already exist - proceed with migration
        </onerror>
    </script>
    <query connection-id="in">
        SELECT user_name,user_pass FROM users;
        <script connection-id="out">
            <!--
            Create user entry
            dn: uid=?user_name,ou=people,dc=scriptella
            objectClass: inetOrgPerson
            uid: ?user_name
            sn: ?user_name
            cn: ?user_name
            userPassword: ?user_pass
            -->
            INSERT INTO uid,ou=people,dc=scriptella (objectClass,uid,sn,cn,userPassword) VALUES (inetOrgPerson,?user_name,?user_name,?user_name,?user_pass);
            <onerror message=".*already exists.*" retry="true">
                <!--If user entry exists - delete it -->
                DELETE FROM ou=people,dc=scriptella WHERE uid=?user_name
            </onerror>
        </script>
    </query>
    <query connection-id="in">
        SELECT DISTINCT role_name FROM user_roles;
        <script connection-id="out">
            <!--
            # Define an entry for the role_name role
            dn: cn=?role_name,ou=groups,dc=scriptella
            objectClass: groupOfUniqueNames
            cn: ?role_name
        -->
            INSERT INTO cn,ou=groups,dc=scriptella (objectClass,cn,uniqueMember) VALUES (groupOfUniqueNames,?role_name,"dc=scriptella");
            <onerror message=".*already exists.*" retry="true">
                <!--If group entry exists - delete it -->
                DELETE FROM ou=groups,dc=scriptella WHERE cn=?role_name
            </onerror>

        </script>
        <query connection-id="in">
            SELECT user_name FROM user_roles WHERE role_name=?role_name;
            <!-- First user replaces artificial uniqueMember: dc=scriptella
                 Note: ?role_name is inserted directly  into statement text,
                 ?{} expressions are injected as prepared statement parameters-->
            <script connection-id="out" if="rownum==1">
                UPDATE ENTRY cn=$role_name,ou=groups,dc=scriptella DO REPLACE SET
                uniqueMember=?{'uid='+user_name+',ou=people,dc=scriptella'};
            </script>
            <!-- Subsequent users are added-->
            <script connection-id="out" if="rownum gt 1">
                UPDATE ENTRY cn=$role_name,ou=groups,dc=scriptella DO ADD SET
                uniqueMember=?{'uid='+user_name+',ou=people,dc=scriptella'};
            </script>
        </query>
    </query>

</etl>

=== scriptella/scriptella-etl/tags/scriptella-parent-1.1/drivers/src/test/scriptella/driver/jexl/EtlVariableITest.xml
<!DOCTYPE etl SYSTEM "http://scriptella.javaforge.com/dtd/etl.dtd">
<etl>
    <connection driver="jexl" id="jexl"/>
    <connection driver="text" id="text" url="tst://file"/>

    <script connection-id="jexl">
        etl.globals['v1'] = '1'
    </script>
    <script connection-id="text">
        ${etl.globals['v1']}
        ${etl.globals['v2']='*v2*'}
    </script>
    <query connection-id="jexl">
        localVar = 'local';
        query.next();
        <script connection-id="text">
            local: ${etl.getParameter('local')?etl.getParameter('localVar'):'null444'}
            global: ${etl.globals['v2']}
        </script>
    </query>

    <query connection-id="jexl">
        i=1;
        while (i lt 3) {
            query.next();
            i=i+1;
        }
        <script connection-id="text">
            i=$i
        </script>
    </query>

    <!-- globals should also be available in if attributes -->
    <script connection-id="text" if="etl.globals['v1']=='1'">
        if_ok
    </script>
</etl>
