=== scriptella/scriptella-etl/core/src/conf/scriptella/dtd/etl.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
%
 Copyright 2006-2012 The Scriptella Project Team.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
%
@title Scriptella ETL File DTD
@doctype etl SYSTEM "http://scriptella.org/dtd/etl.dtd"
@root etl
-->

<!--
Root element of Scriptella XML file.
<p><u>Example:</u><br>
A simple example of the script file with only one connection obtained via
JNDI bound datasource.
%
<etl>
    <connection driver="jndi" url="java:projectDS"/>
    <script>
        INSERT INTO Test VALUES (1, "One")
    </script>
</etl>

%
-->
<!ELEMENT etl (description?, properties?, connection*, (script*, query*)*)>

<!--
Contains description of ETL file.
-->
<!ELEMENT description (#PCDATA)>
<!--
The properties element contains a set of properties available for script elements.
The content of this element conforms to format supported by java.util.Properties.
This element may contain plain text or includes.
<p><u>Example:</u>
%
<properties>
    #standard properties syntax
    table.size=10
    tmp=c\:\\temp\\
    #including content from external properties file
    <include href="etl.properties"/>
</properties>

-->
<!ELEMENT properties (#PCDATA | include)*>
<!--
The connection element specifies connection to a database or other system.
This element may contain properties as plain text with includes.
<p><u>Example:</u>
%
<connection id="in" driver="com.octetstring.jdbcLdap.sql.JdbcLdapDriver"
            url="jdbc:ldap://localhost:389/dc=scriptella"
            user="cn=root,dc=scriptella" password="secret">
    SEARCH_SCOPE=subTreeScope
    ignore_transactions=true
</connection>

<connection driver="h2"
            url="jdbc:h2:db"
            user="sa" classpath="h2.jar"/>
%
-->
<!ELEMENT connection (#PCDATA | include)*>
<!--
 @attr id connection identifier. Connection is referenced by id in scripts and queries.
       For single connection ETL files this attribute is optional.
 @attr driver driver class name or alias. The default value is "auto",
       in this case a target driver is guessed from an url attribute.
 @attr url connection url.
 @attr user database login
 @attr password database password
 @attr catalog catalog
 @attr schema schema
 @attr classpath the classpath to use when loading the driver.
       Paths are colon/semicolon separated and resolved relative to a directory where ETL file resides.
       Absolute URLs are also supported, e.g. ftp://server/lib.jar
 @attr lazy-init <b>true</b> if connection initialization should be deferred until it is actually used.
       The default value of <b>false</b> means that connection is initialized on ETL startup.
-->
<!ATTLIST connection
id ID #IMPLIED
driver CDATA "auto"
url CDATA #IMPLIED
user CDATA #IMPLIED
password CDATA #IMPLIED
catalog CDATA #IMPLIED
schema CDATA #IMPLIED
classpath CDATA #IMPLIED
lazy-init (true | false) "false"
>
<!--
The fallback element contains alternate content to be used if the requested resource cannot be found.
This element may contain plain text or includes.
<p><u>Example:</u>
%
<include href="http://no-such-url/file.txt">
    <fallback> //First fallback
        <include href="localFile.txt>
            <fallback> //If alternative location also failed
                Failed to retrieve full text
            </fallback>
        </include>
    </fallback>
</include>
%
-->
<!ELEMENT fallback (#PCDATA | include)*>

<!--
The include element specifies content to include. Concept similar to XInclude.
<p><u>Examples:</u>
%
<include href="http://host/file.sql"><fallback>SHUTDOWN</fallback></include>
<include href="db/schema.sql"/>
%
-->
<!ELEMENT include (fallback?)>
<!--
@attr href contains an URI pointing to the file to include. URIs are resolved relative to ETL file.
@attr encoding Included text encoding name.
-->
<!ATTLIST include
href CDATA #REQUIRED
encoding CDATA #IMPLIED
>
<!--
The dialect element defines a vendor specific script. Scripting elements may contain any number of nested dialects.
This element may contain plain text or includes.
<u>Example:</u>
%
<dialect name="oracle" version="10\.">
    //Statements executed only for Oracle 10.x
</dialect>
<dialect name="oracle" exclude="true">
    //Statements executed for any datasource except Oracle
</dialect>

%
-->
<!ELEMENT dialect (#PCDATA | include)*>
<!--
 @attr name case insensitive regular expression to match vendor name, e.g. .*oracle.*
 @attr version case insensitive regular expression to match vendor version, e.g. 1\.0
 @attr exclude optional attribute to invert the name/version matching.
       Use exclude="true" to skip content for dialects with specified name and version.

-->
<!ATTLIST dialect
name CDATA #IMPLIED
version CDATA #IMPLIED
exclude (true | false) "false"
>

<!--
The onerror element defines fallback script to execute if error occurs.
This element may contain plain text or includes.
<p><u>Example:</u>
%
<onerror type="SQLException">
    DROP TABLE MYTABLE
</onerror>
%
Note: Attributes are applied using AND condition, so if you specified
%<onerror type="ProviderException" codes="100,200">%
so only exceptions with class name *.ProviderException having 100 and/or 200 error code are handled.
-->
<!ELEMENT onerror (#PCDATA | include | dialect)*>
<!--
 @attr type Regular expression pattern to match exception type. Partial matching is allowed.
 @attr codes Comma-separated list of vendor codes/sql states. Triggered if any of these codes matches one of the codes reported by driver.
 @attr message Regular expression pattern to match exception message. Partial matching is allowed.
 @attr retry true if statement which caused a problem should be retried after this handler completes.
 @attr connection-id optional connection ID. If omitted, the error handling code will be executed in the context of the current connection.
-->
<!ATTLIST onerror
type CDATA #IMPLIED
codes CDATA #IMPLIED
message CDATA #IMPLIED
retry (true | false) "false"
connection-id IDREF #IMPLIED
>

<!--
The query element is used to specify a query producing a result set.
This element may contain queries, scripts, plain text, includes and dialects.
<p><u>Example:</u><br>
Queries a table and writes the result into CSV file
%
<query connection-id="in">
   SELECT * FROM Test WHERE id=&#063;id
   <script connection-id="csv">
        $id,$value
   </script>
</query>
%
-->
<!ELEMENT query (#PCDATA | include | dialect | query | script)*>
<!--
 @attr connection-id references connection by identifier. The value of this attribute is inherited for nested elements.
       For single connection ETL files the connection-id is optional.
 @attr if expression to test. If result of evaluation is true - the element is evaluated, otherwise skipped.
        Use <a href="http://jakarta.apache.org/commons/jexl">JEXL</a> syntax for expressions.
 @attr id script identifier(name).
-->
<!ATTLIST query
connection-id IDREF #IMPLIED
if CDATA #IMPLIED
id ID #IMPLIED
>

<!--
The script element is used to specify a script.
This element may contain plain text,onerror handlers, includes and dialects.
<p><u>Example:</u><br>
Inserts a row into Test table if id>0
%
<script if="id>0">
    INSERT INTO Test VALUES(&#063;id, &#063;name)
</script>
%
-->
<!ELEMENT script (#PCDATA | include | dialect | onerror)*>
<!--
 @attr connection-id references connection by identifier. The value of this attribute is inherited for nested elements.
       For single connection ETL files the connection-id is optional.
 @attr new-tx true to use a separate connection for this script element. Opened lazily and reused across invocations; not committed after each invocation.
 @attr if expression to test. If result of evaluation is true - the element is evaluated, otherwise skipped.
        Use <a href="http://jakarta.apache.org/commons/jexl">JEXL</a> syntax for expressions.
 @attr id script identifier(name).
-->
<!ATTLIST script
connection-id IDREF #IMPLIED
new-tx (true | false) "false"
if CDATA #IMPLIED
id ID #IMPLIED
>

=== scriptella/scriptella-etl/samples/ldap/jdbc/ldap2db.etl.xml
<!DOCTYPE etl SYSTEM "http://scriptella.org/dtd/etl.dtd">
<etl>
    <description>
        Migrates data from LDAP to Database.
        Creates users and roles tables suitable for Tomcat JDBCRealm authentication.
        The source data is obtained from LDAP.
    </description>
    <!--Connection to the LDAP-->
    <connection id="in" driver="com.octetstring.jdbcLdap.sql.JdbcLdapDriver"
                url="jdbc:ldap://localhost:389/dc=scriptella"
                user="cn=root,dc=scriptella" password="secret" classpath="../lib/jdbcldap.jar">
        <!--Define connection properties-->
        SEARCH_SCOPE=subTreeScope
        ignore_transactions=true
        <!--You may embed properties into url using driver specific syntax, e.g.
         jdbc:ldap://localhost:389/dc=scriptella?SEARCH_SCOPE:=subTreeScope&amp;ignore_transactions:=true
         -->
    </connection>
    <!--Connection to the target database -->
    <connection id="out" driver="org.h2.Driver" url="jdbc:h2:./outdb"
                user="sa" password="" classpath="../lib/h2.jar"/>
    <script connection-id="out">
        <!--Creates empty database and drops exisiting tables if DB already exisis -->
        <include href="../dbschema.sql"/>
    </script>
    <query connection-id="in">
        <!--Selects users(user attributes) from ou=people,dc=scriptella-->
        SELECT uid,userPassword,DN FROM ou=people WHERE objectClass = 'inetOrgPerson'
        <!--For each found user executes the following script-->
        <script connection-id="out">
            <!--Inserts user record using parameters from the outer query result set-->
            INSERT INTO Users VALUES (?uid, ?userPassword);
        </script>
        <!--Additionally we need to query a list of groups containing found user-->
        <query>
            <!-- ldapsearch.exe -b dc=scriptella "(&(objectClass=groupOfUniqueNames)(uniqueMember=?DN))" -->
            SELECT cn FROM ou=groups WHERE objectClass = 'groupOfUniqueNames' and uniqueMember=?DN
            <!-- For each group in the query result set-->
            <script connection-id="out">
                <!--Insert User_Role record into database-->
                INSERT INTO User_Roles VALUES (?uid, ?cn);
            </script>
        </query>
    </query>
</etl>

=== scriptella/scriptella-etl/core/src/test/scriptella/jdbc/NestedElementsPerfTest.xml
<!DOCTYPE etl SYSTEM "http://scriptella.org/dtd/etl.dtd">
<etl>
    <connection driver="org.h2.Driver" url="jdbc:h2:mem:nestedElements;MODE=LEGACY;NON_KEYWORDS=VALUE" user="sa"/>
    <script>
        CREATE TABLE Test (
        ID INT
        );
        INSERT INTO TEST VALUES (1);
        INSERT INTO TEST VALUES (2);
        INSERT INTO TEST VALUES (3);
        INSERT INTO TEST VALUES (4);
        INSERT INTO TEST VALUES (5);
        INSERT INTO TEST VALUES (6);
        INSERT INTO TEST VALUES (7);
        INSERT INTO TEST VALUES (8);
        INSERT INTO TEST VALUES (9);
        INSERT INTO TEST VALUES (10);
    </script>
    <query>
        SELECT * FROM Test
        <query>
            SELECT * FROM Test
            <query>
                SELECT * FROM Test
                <query>
                    SELECT * FROM Test
                    <script>
                        UPDATE TEST SET id=100 where id=-1;
                    </script>
                </query>

            </query>
        </query>
    </query>
    <query>
        SELECT * FROM Test
        <query>
            SELECT * FROM Test
            <query>
                SELECT * FROM Test
                <query>
                    SELECT * FROM Test
                    <script>
                        UPDATE TEST SET id=?id where id=-1;
                    </script>
                </query>

            </query>
        </query>


    </query>

    <script>
    </script>


</etl>

=== scriptella/scriptella-etl/core/src/test/scriptella/OnErrorTest.xml
<!DOCTYPE etl SYSTEM "http://scriptella.org/dtd/etl.dtd">
<etl>
    <connection driver="org.h2.Driver" url="jdbc:h2:mem:onerrortest;MODE=LEGACY;NON_KEYWORDS=VALUE" user="sa" password=""/>
    <script>
        CREATE TABLE Test (
            COL INT
        );
    </script>
    <script>
        CREATE TABLE Test (
            ID INT NOT NULL PRIMARY KEY,
            VALUE VARCHAR(255)
        );
        insert into test(id, value) values (1,'111');
        insert into test(id, value) values (2,'222');
        insert into test(id, value) values (3,'333');
        insert into test(id, value) values (5,'555');
        <onerror codes="99999,22222,33333">
            --does nothing so test should fail
        </onerror>
        <onerror retry="true" codes="???,42101"><!--42101 means table already exists in H2-->
            DROP TABLE Test;
        </onerror>
    </script>
    <script>
        insert into test(id, value) values (1,'Updated');
        <onerror>
            <dialect name="fakedb">
                skipped text
            </dialect>
            UPDATE test set value='Updated1' where ID=1;
        </onerror>
    </script>
    <script>
        insert into test(id, value) values (2,'Updated');<!--Already exists-->
        <onerror><!-- Fails too-->
            insert into test(id, value) values (2,'Updated');
        </onerror>
        <onerror message="Unique index"><!--Updates-->
            <dialect name="h2">
                UPDATE test set value='Updated2' where ID=2;
            </dialect>
        </onerror>
    </script>
    <script>
        insert into test(id, value) values (3,'Updated');<!--Already exists-->
        <onerror type="JDBCException"><!--Updates-->
            UPDATE test set value='Updated3' where ID=3;
        </onerror>
    </script>
    <script>
        insert into test(id, value) values (4,'444');
        <onerror><!--should not fire-->
            UPDATE test set value='Updated4' where ID=4;
        </onerror>
    </script>
    <script>
        insert into test(id, value) values (5,'New value');
        <onerror type="NoSuchException"><!--Updates-->
            UPDATE test set value='Updated5' where ID=5;
        </onerror>
        <onerror/><!--means ignoring any exception-->
    </script>


</etl>

=== scriptella/scriptella-etl/tags/scriptella-parent-1.1/drivers/src/test/scriptella/driver/text/TextFormattingITest.xml
<!--
  ~ Copyright 2006-2012 The Scriptella Project Team.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<!DOCTYPE etl SYSTEM "http://scriptella.javaforge.com/dtd/etl.dtd">
<etl>
    <connection id="db" driver="hsqldb" url="jdbc:hsqldb:mem:text" user="sa" password=""/>

    <connection id="text" driver="text" url="tst://testfile">
        format.2.trim=true
        format.Text.trim=true
        format.DateCol.type=date
        format.DateCol.pattern=dd-MM-yyyy HH:mm
        #4 column mapped to DateCol
        format.4.type=date
        format.4.pattern=dd-MM-yyyy HH:mm
        format.NumCol.type=number
        format.NumCol.trim=true
        format.NumCol.pattern=#.00
        format.NumCol.null_string=-null-
        #5 column mapped to NumCol
        format.column5.type=number
        format.column5.pattern=#.00
        format.column5.null_string=-null-
    </connection>

    <script connection-id="db">
        <!-- Test data -->
        CREATE TABLE Test (
            ID INT,
            Text VARCHAR(100),
            TextNoTrim VARCHAR(100),
            DateCol TIMESTAMP,
            NumCol DECIMAL
        );
        INSERT INTO Test VALUES(1, 'One', 'One', {ts '2012-07-11 22:33:44.1'}, null);
        INSERT INTO Test VALUES(2, ' Two ', ' Two ', {ts '2012-07-11 20:00:00'}, 2.1);
        INSERT INTO Test VALUES(3, ' Three ', ' Three ', {ts '2012-07-11 20:00:00'}, 3.1);
        CREATE TABLE TestAlias (
            NumCol DECIMAL
        );
    </script>

    <!-- Reads input and inserts into a Test table. column format rules are used to parse values -->
    <query connection-id="text">
        ([\d]+),([^,]*),([^,]*),([^,]*),([^,]*)
        <script connection-id="db">
            INSERT INTO Test VALUES(?1, ?2, ?3, ?4, ?column5); <!-- ?column5=?5 -->
        </script>
    </query>


    <!-- Export DB to a CSV file -->
    <query connection-id="db">
        SELECT * FROM Test
        <script connection-id="text">
            $Id/$Text/$TextNoTrim/$DateCol/$NumCol
        </script>
    </query>

</etl>

=== scriptella/scriptella-etl/samples/ldap/ldap2db.etl.xml
<!DOCTYPE etl SYSTEM "http://scriptella.org/dtd/etl.dtd">
<etl>
    <description>
        Migrates data from LDAP to Database.
        Creates users and roles tables suitable for Tomcat JDBCRealm authentication.
        The source data is obtained from LDAP.
    </description>
    <!--Connection to the LDAP-->
    <connection id="in" url="ldap://localhost:389/dc=scriptella"
                user="cn=root,dc=scriptella" password="secret">
        <!--Define connection properties-->
        search.scope=subtree
    </connection>
    <!--Connection to the target database -->
    <connection id="out" url="jdbc:h2:./outdb"
                user="sa" password="" classpath="../lib/h2.jar"/>
    <script connection-id="out">
        <!--Creates empty database and drops exisiting tables if DB already exisis -->
        <include href="dbschema.sql"/>
    </script>
    <query connection-id="in">
        <!--Selects users(user attributes) from ou=people,dc=scriptella-->
        (objectClass=inetOrgPerson)
        <script connection-id="out">
            <!--Inserts user record using parameters from the outer query result set-->
            <!--Please note that userPassword is just a hash of the original value-->
            INSERT INTO Users VALUES (?uid, ?userPassword);
        </script>
        <!--Additionally we need to query a list of groups containing found user-->
        <query>
            <![CDATA[(&(objectClass=groupOfUniqueNames)(uniqueMember=$dn))]]>
            <!-- For each group in the query result set-->
            <script connection-id="out">
                <!--Insert User_Role record into database-->
                INSERT INTO User_Roles VALUES (?uid, ?cn);
            </script>
        </query>
    </query>
</etl>

=== scriptella/scriptella-etl/tags/1_0_rc2/core/src/test/scriptella/DialectsTest.xml
<!DOCTYPE etl SYSTEM "http://scriptella.javaforge.com/dtd/etl.dtd">
<etl>
    <connection driver="org.hsqldb.jdbcDriver" url="jdbc:hsqldb:mem:dialectstest" user="sa" password=""/>
    <script>
        <!--must execute-->
        CREATE TABLE Test (
        ID INT,
        VALUE VARCHAR(255)
        );
    </script>
    <script>
        <!--must execute-->
        insert into test(id, value) values (1,'222');
    </script>
    <script>
        <dialect name=".*oracle.*"><!--Skipped-->
            insert into test(id, value) values (2,'333');
        </dialect>
    </script>
    <script>
        <dialect name="hsql.*"><!--must execute-->
            insert into test(id, value) values (3,'333');
        </dialect>
        <dialect name=""><!--executes-->
            insert into test(id, value) values (4,'333');
        </dialect>
    </script>
    <script>
        <dialect><!--must execute-->
            insert into test(id, value) values (5,'333');
        </dialect>
    </script>
    <script>
        <dialect name="HSQL.*" version="1\.8\..*"><!--must execute-->
            insert into test(id, value) values (6,'333');
        </dialect>
        <dialect name="hsql.*" version="1.8.*"><!--executes-->
            insert into test(id, value) values (7,'333');
        </dialect>
        <dialect name="hsql.*" version="1\.9.*"><!--skipped-->
            insert into test(id, value) values (8,'333');
        </dialect>
        insert into test(id, value) values (9,'333');

    </script>
    <script>
        <dialect name="hsql" exclude="true"><!-- skipped -->
            insert into test(id, value) values (10,'333');
        </dialect>
        <dialect name="oracle" exclude="true"> <!-- executes-->
            insert into test(id, value) values (11,'333');
        </dialect>

    </script>


</etl>

=== scriptella/scriptella-etl/core/src/test/scriptella/DialectsTest.xml
<!DOCTYPE etl SYSTEM "http://scriptella.org/dtd/etl.dtd">
<etl>
    <connection driver="org.h2.Driver" url="jdbc:h2:mem:dialectstest;MODE=LEGACY;NON_KEYWORDS=VALUE" user="sa" password=""/>
    <script>
        <!--must execute-->
        CREATE TABLE Test (
        ID INT,
        VALUE VARCHAR(255)
        );
    </script>
    <script>
        <!--must execute-->
        insert into test(id, value) values (1,'222');
    </script>
    <script>
        <dialect name=".*oracle.*"><!--Skipped-->
            insert into test(id, value) values (2,'333');
        </dialect>
    </script>
    <script>
        <dialect name="h2"><!--must execute-->
            insert into test(id, value) values (3,'333');
        </dialect>
        <dialect name=""><!--executes-->
            insert into test(id, value) values (4,'333');
        </dialect>
    </script>
    <script>
        <dialect><!--must execute-->
            insert into test(id, value) values (5,'333');
        </dialect>
    </script>
    <script>
        <dialect name="H2" version="2\.4\..*"><!--must execute-->
            insert into test(id, value) values (6,'333');
        </dialect>
        <dialect name="h2" version="2.4.*"><!--executes-->
            insert into test(id, value) values (7,'333');
        </dialect>
        <dialect name="h2" version="2\.3.*"><!--skipped-->
            insert into test(id, value) values (8,'333');
        </dialect>
        insert into test(id, value) values (9,'333');

    </script>
    <script>
        <dialect name="h2" exclude="true"><!-- skipped -->
            insert into test(id, value) values (10,'333');
        </dialect>
        <dialect name="oracle" exclude="true"> <!-- executes-->
            insert into test(id, value) values (11,'333');
        </dialect>

    </script>


</etl>

=== scriptella/scriptella-etl/drivers/src/test/scriptella/driver/xpath/XPathDriverITest.xml
<!DOCTYPE etl SYSTEM "http://scriptella.org/dtd/etl.dtd">
<etl>
    <properties>
        xpath=/Workbook/Worksheet/Table/Row
    </properties>
    <connection id="in1" driver="xpath" url="excel.xml">
        return_arrays=true
    </connection>
    <connection id="in2" driver="xpath" url="xml1.xml"/>
    <connection id="in3" driver="xpath" url="xml2.xml"/>
    <connection id="out" driver="text" url="tst://testfile"/>


    <query connection-id="in1" if="test==1">
        ${xpath}
        <script connection-id="out">${Cell[0]};${Cell[1]}</script>
    </query>

    <!-- Test2: Querying the same datasource. Joining <tr><td>1</td> with <th>Col1</th> -->
    <query connection-id="in2" if="test==2">
        /html/body/table/tr[2]/td[1]
        <query>
            /html/body/table/tr/th[2]
            <script connection-id="out">$td;$th</script>
        </query>
    </query>

    <!-- Test3: Querying the same datasource.
        Using relative xpaths select tr[2]/td[2] -->
    <query connection-id="in2" if="test==3">
        /html/body/table/tr[2]
        <query>
            ./td[2]
            <script connection-id="out">$td</script>
        </query>
    </query>

    <!-- Test4: Querying 2 datasources.
   Using relative xpaths select tr[2]/td[2] -->
    <query connection-id="in2" if="test==4">
        /html/body/table/tr[2]/td[1] <!-- <td>1</td> -->
        <query connection-id="in3">
            <!-- select <element attribute=1><attribute>2</attribute></element> -->
            /xml/element[@attribute=$td]
            <script connection-id="out">$td;$element</script>
        </query>
    </query>

    <!-- Test5: History test for bug when query is overriding context of the sibling -->
    <query connection-id="in2" if="test==5">
        /html/body/table/tr[2]
        <query>
            ./td[1]
        </query>
        <query>
            ./td[2]
            <script connection-id="out">$td</script>
        </query>
    </query>

    <!-- Test6: Relative querying with 'node' variable.
        Using relative xpaths select tr[2]/td[2] and tr[3]/td[2] -->
    <query connection-id="in2" if="test==6">
        /html/body/table
        <script connection-id="out">${node.getString("./tr[2]/td[2]")};${node.getString("./tr[3]/td[2]")}</script>
    </query>
</etl>
